twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/tailwind_form.html.twig']
    globals:
        recaptcha_site_key: '%site_key%'
        ticker: '%cointicker%'
        coinname: '%coinname%'
        claim_min: '%claim_min%'
        claim_max: '%claim_max%'
        mode: '%payout_mode%'
        staged_payouts: '%staged_payouts%'
        payout_time: '%payout_time%'
        claim_difference: '%claim_difference%'
        ad_top: '%ad_top%'
        ad_center: '%ad_center%'
        ad_left: '%ad_left%'
        ad_right: '%ad_right%'
        adblock_blocker: '%adblock_blocker%'