parameters:
  # Coin
  coinname: 'Dash'
  cointicker: 'Dash'

  # Wallet
  rpchost: '127.0.0.1'
  rpcport: '9998'
  rpcuser: 'faucet'
  rpcpassword: 'faucetpay'
  single_payout: false

  # Faucet mode
  claim_min: 1 # Set Amount to claim, amount will be randomly choosen between claim_min and claim_max. If claim_min = claim_max it will always payout the same amount
  claim_max: 2 # To use fiat values add a $ or € sign (example: 1€, or 2.5$) -> please check that the coinname exists on coingecko
  claim_difference: 200 # Time between claims in seconds
  payout_mode: 'timed' # Payout mode, available: (staged => pay out when STAGED_PAYOUTS payments are in the queue, timed => pay out each x seconds)
  staged_payouts: 5
  payout_time: 3600 # Seconds between each payments, please set the cronjob according to this (reference in Readme)

  # Captcha
  provider: 'hcaptcha' # recaptcha coming soon
  secret: ''
  site_key: ''

  # Frontend
  ad_top: true
  ad_center: true
  adblock_blocker: true
  background: true
  custom_text: ''